In [1]:
import numpy as np 


Escalares 

In [3]:
x=np.array(42)
print(x.shape)
x.ndim

()


0

Vector


In [4]:
x=np.array([1,2,3])
print(x.shape)
x.ndim

(3,)


1

Matrix


In [5]:
x=np.array([[1,2,3],[4,5,6]])
print(x.shape)
x.ndim

(2, 3)


2

Tensor

In [7]:
x=np.array([[[1,2,3],[4,5,6],[98,8,5]],[[1,2,3],[4,5,6],[98,8,5]]   ])
print(x.shape)
x.ndim

(2, 3, 3)


3

Reshape

In [9]:
x=np.array([
    [0,1],
    [5,9],
    [1,6],
    [5,7],

    
          
          
          ]   )
x.shape

(4, 2)

In [10]:
x.reshape(8,1)

array([[0],
       [1],
       [5],
       [9],
       [1],
       [6],
       [5],
       [7]])

In [11]:
x.reshape(2,4)

array([[0, 1, 5, 9],
       [1, 6, 5, 7]])

In [12]:
np.transpose(x)

array([[0, 5, 1, 5],
       [1, 9, 6, 7]])

In [13]:
x.T

array([[0, 5, 1, 5],
       [1, 9, 6, 7]])